### DISCUSSION TITLE
How to automatically challenge another bot with a time of 30s or 45s

### DISCUSSION THREAD

**Discussion by M-DinhHoangViet** [lichess-bot-devs/lichess-bot#776] [Q&A] [answered]
How to automatically challenge another bot with a time of 30s or 45s
I already know how to create auto challenge with initial time of 1+0, 1+1 or 0+1 but I want to challenge 30s+1 and 45s+1 but can't

**Comment by AttackingOrDefending** [comment, marked as answer]
In your `config.yml` you can add `30` under `challenge_initial_time` and `1` under `challenge_increment`, and your bot will play 30+1.
```yml
matchmaking:
  challenge_initial_time:     # Initial time in seconds of the challenge (to be chosen at random).
    - 30
    - 45
  challenge_increment:        # Increment in seconds of the challenge (to be chosen at random).
    - 1
```
