### ISSUE TITLE
UnboundLocalError: local variable 'move' referenced before assignment

### ISSUE THREAD

**Issue by TheYoBots** [lichess-bot-devs/lichess-bot#749]
Relevant normal logs:
```
[06/21/23 20:28:35] INFO     Backing off play_game(...) for       _common.py:105
                             189.6s (UnboundLocalError: local                   
                             variable 'move' referenced before                  
                             assignment) 
```
Relavant verbose logs:
```
                    INFO     Backing off play_game(...) for 1.0s  _common.py:105
                             (UnboundLocalError: local variable                 
                             'move' referenced before assignment)               
                    DEBUG    Backing off 1.0 seconds after 1 tries lichess.py:62
                             calling function <function play_game               
                             at 0x7f72f40d6af0> with args () and                
                             kwargs {'li': <lichess.Lichess object              
                             at 0x7f72f5bd6070>, 'control_queue': ...
                             ...
                    DEBUG    Exception: Traceback (most recent     lichess.py:64
                             call last):                                        
                             File                                             
                             "/usr/local/lib/python3.9/dist-packag              
                             es/backoff/_sync.py", line 105, in                 
                             retry                                              
                                 ret = target(*args, **kwargs)                  
                               File "//lichess/lichess-bot.py",                 
                             line 620, in play_game                             
                                 engine.play_move(board,                        
                               File "/lichess/engine_wrapper.py",               
                             line 160, in play_move                             
                                 best_move = get_book_move(board,               
                             game, polyglot_cfg)                                
                               File "/lichess/engine_wrapper.py",               
                             line 704, in get_book_move                         
                                 if move is not None:                           
                             UnboundLocalError: local variable                  
                             'move' referenced before assignment
```

**Comment by MarkZH** [comment]
Can you post the `engine: polyglot:` section of your config?

**Comment by TheYoBots** [comment]
```yml
polyglot:
    enabled: true            # Activate polyglot book.
    book:
      standard:              # List of book file paths for variant standard.
        - lichess/book1.bin
        - lichess/book2.bin
        - lichess/book3.bin
        - lichess/book3.bin
#     atomic:                # List of book file paths for variant atomic.
#       - engines/atomicbook1.bin
#       - engines/atomicbook2.bin
#     etc.
#     Use the same pattern for 'giveaway' (antichess), 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
```

The dir is correct. When I put a wrong dir I get the following error:
```
                             Backing off play_game(...) for       _common.py:105
                             107.3s (FileNotFoundError: [Errno 2]               
                             No such file or directory:                         
                             'Perfect2021.bin')
```

**Comment by TheYoBots** [comment]
I found my error... instead of `"best"` I put `"bets"` by mistake:
```yml
chessdb_book:
      enabled: true
      min_time: 30
      move_quality: "bets"   # One of "all", "good", "best".
      min_depth: 30          # Only for move_quality: "best".
```
Really sorry for the inconvenience! Thanks for helping :)
